export const phones = [
  { deviceName: "infinix", deviceModel: "Spark 10P" },
  { deviceName: "infinix", deviceModel: "Spark 10 Pro 5G" },
  { deviceName: "infinix", deviceModel: "Pova 5 Neo" },
  { deviceName: "infinix", deviceModel: "Pova 5" },
  { deviceName: "infinix", deviceModel: "Camon 20 Premier" },
  { deviceName: "infinix", deviceModel: "Camon 20 Pro" },
  { deviceName: "infinix", deviceModel: "Spark 10C" },
  { deviceName: "infinix", deviceModel: "Spark 10" },
  { deviceName: "infinix", deviceModel: "Pova 5 Pro" },
  { deviceName: "infinix", deviceModel: "Spark 20C" },
  { deviceName: "infinix", deviceModel: "Spark Go 2023" },
  { deviceName: "infinix", deviceModel: "Spark 20" },
  { deviceName: "infinix", deviceModel: "Spark 20 Pro" },
  { deviceName: "infinix", deviceModel: "Phantom V Flip" },
  { deviceName: "infinix", deviceModel: "Phantom V Fold" },
  { deviceName: "infinix", deviceModel: "Pova 5 Neo 5G" },
  { deviceName: "infinix", deviceModel: "Spark Go 2022" },
  { deviceName: "infinix", deviceModel: "Phantom X2" },
  { deviceName: "infinix", deviceModel: "Pova 4 Pro" },
  { deviceName: "infinix", deviceModel: "Camon 19 Pro" },
  { deviceName: "infinix", deviceModel: "Camon 20 Pro 5G" },
  { deviceName: "infinix", deviceModel: "Spark 10T" },
  { deviceName: "infinix", deviceModel: "Spark 10 Pro" },
  { deviceName: "infinix", deviceModel: "Spark Go 6" },
  { deviceName: "infinix", deviceModel: "Pova 5" },
  { deviceName: "infinix", deviceModel: "Spark 10T" },
  { deviceName: "infinix", deviceModel: "Spark Go" },
  { deviceName: "infinix", deviceModel: "Pova 5 Neo 5G" },
  { deviceName: "infinix", deviceModel: "Pova 5 Neo" },
  { deviceName: "infinix", deviceModel: "Spark 10" },
  { deviceName: "infinix", deviceModel: "Spark 10T" },
  { deviceName: "infinix", deviceModel: "Camon 19 Pro" },
  { deviceName: "infinix", deviceModel: "Camon 20 Pro 5G" },
  { deviceName: "infinix", deviceModel: "Spark 10C" },
  { deviceName: "infinix", deviceModel: "Spark Go" },
  { deviceName: "infinix", deviceModel: "Spark Go 6" },
  { deviceName: "infinix", deviceModel: "Spark 10 Pro" },
  { deviceName: "infinix", deviceModel: "Phantom V Fold" },
  { deviceName: "infinix", deviceModel: "Pop 5G" },
  { deviceName: "infinix", deviceModel: "Spark 10C" },
  { deviceName: "infinix", deviceModel: "Pop 5 Pro" },
  { deviceName: "infinix", deviceModel: "Spark 9 Pro" },
  { deviceName: "infinix", deviceModel: "Spark 10T" },
  { deviceName: "infinix", deviceModel: "Spark 8T" },
  { deviceName: "infinix", deviceModel: "Spark Go 2022" },
  { deviceName: "infinix", deviceModel: "Pova 5G" },
  { deviceName: "infinix", deviceModel: "Pova Neo" },
  { deviceName: "infinix", deviceModel: "Camon 18T" },
  { deviceName: "infinix", deviceModel: "Pop 5 LTE" },
  { deviceName: "infinix", deviceModel: "Pop 5C" },
  { deviceName: "infinix", deviceModel: "Camon 18i" },
  { deviceName: "infinix", deviceModel: "Camon 18 Premier" },
  { deviceName: "infinix", deviceModel: "Camon 18P" },
  { deviceName: "infinix", deviceModel: "Spark 8" },
  { deviceName: "infinix", deviceModel: "Pop 5" },
  { deviceName: "infinix", deviceModel: "Spark Go 2021" },
  { deviceName: "infinix", deviceModel: "Spark 7T" },
  { deviceName: "infinix", deviceModel: "Phantom X" },
  { deviceName: "infinix", deviceModel: "Pova 2" },
  { deviceName: "infinix", deviceModel: "Camon 17 Pro" },
  { deviceName: "infinix", deviceModel: "Camon 17P" },
  { deviceName: "infinix", deviceModel: "Camon 17" },
  { deviceName: "infinix", deviceModel: "Spark 7 Pro" },
  { deviceName: "infinix", deviceModel: "Spark 7" },
  { deviceName: "infinix", deviceModel: "Camon 16 Pro" },
  { deviceName: "infinix", deviceModel: "Camon 16" },
  { deviceName: "infinix", deviceModel: "Spark 6" },
  { deviceName: "infinix", deviceModel: "Spark Go 2020" },
  { deviceName: "infinix", deviceModel: "Pova" },
  { deviceName: "infinix", deviceModel: "Camon 16" },
  { deviceName: "infinix", deviceModel: "Spark 6 Air" },
  { deviceName: "infinix", deviceModel: "Camon 16 Premier" },
  { deviceName: "infinix", deviceModel: "Pova 4 Pro" },
  { deviceName: "infinix", deviceModel: "Pop 4" },
  { deviceName: "infinix", deviceModel: "Pova 2" },
  { deviceName: "infinix", deviceModel: "Spark Power 2" },
  { deviceName: "infinix", deviceModel: "Spark 8 Air" },
  { deviceName: "infinix", deviceModel: "Spark 6 Pro" },
  { deviceName: "infinix", deviceModel: "Spark 6" },
  { deviceName: "infinix", deviceModel: "Camon 15 Premier" },
  { deviceName: "infinix", deviceModel: "Spark 7 Pro" },
  { deviceName: "infinix", deviceModel: "Camon 15 Pro" },
  { deviceName: "infinix", deviceModel: "Spark 6" },
  { deviceName: "infinix", deviceModel: "Camon 12 Air" },
  { deviceName: "infinix", deviceModel: "Smart 2 Plus" },
  { deviceName: "infinix", deviceModel: "S4" },
  { deviceName: "infinix", deviceModel: "Hot 7 Pro" },
  { deviceName: "infinix", deviceModel: "Hot 7" },
  { deviceName: "infinix", deviceModel: "Zero 6 Pro" },
  { deviceName: "infinix", deviceModel: "Zero 6" },
  { deviceName: "infinix", deviceModel: "Smart 2 HD" },
  { deviceName: "infinix", deviceModel: "Hot 6X" },
  { deviceName: "infinix", deviceModel: "Note 5 Stylus" },
  { deviceName: "infinix", deviceModel: "S3X" },
  { deviceName: "infinix", deviceModel: "Hot 6" },
  { deviceName: "infinix", deviceModel: "Smart 2 Pro" },
  { deviceName: "infinix", deviceModel: "Smart 2" },
  { deviceName: "infinix", deviceModel: "Hot 6 Pro" },
  { deviceName: "infinix", deviceModel: "Hot S3" },
  { deviceName: "infinix", deviceModel: "Zero 5 Pro" },
  { deviceName: "infinix", deviceModel: "Zero 5" },
  { deviceName: "infinix", deviceModel: "Hot 5 Lite" },
  { deviceName: "infinix", deviceModel: "Hot 5" },
  { deviceName: "infinix", deviceModel: "Note 5 Pro" },
  { deviceName: "infinix", deviceModel: "Note 4" },
  { deviceName: "infinix", deviceModel: "Smart" },
  { deviceName: "infinix", deviceModel: "Zero 4 Plus" },
  { deviceName: "infinix", deviceModel: "Zero 4" },
  { deviceName: "infinix", deviceModel: "S2 Pro" },
  { deviceName: "infinix", deviceModel: "Zero 4 Pro" },
  { deviceName: "infinix", deviceModel: "Note 3 Pro" },
  { deviceName: "infinix", deviceModel: "Note 4" },
  { deviceName: "tecno", deviceModel: "Spark 10P" },
  { deviceName: "tecno", deviceModel: "Spark 10 Pro 5G" },
  { deviceName: "tecno", deviceModel: "Pova 5 Neo" },
  { deviceName: "tecno", deviceModel: "Pova 5" },
  { deviceName: "tecno", deviceModel: "Camon 20 Premier" },
  { deviceName: "tecno", deviceModel: "Camon 20 Pro" },
  { deviceName: "tecno", deviceModel: "Camon 20 5G" },
  { deviceName: "tecno", deviceModel: "Spark 20 Pro" },
  { deviceName: "tecno", deviceModel: "Spark 20C" },
  { deviceName: "tecno", deviceModel: "Spark Go 2024" },
  { deviceName: "tecno", deviceModel: "Spark 20" },
  { deviceName: "tecno", deviceModel: "Spark 20 Pro" },
  { deviceName: "tecno", deviceModel: "Phantom V Flip" },
  { deviceName: "tecno", deviceModel: "Phantom V Fold" },
  { deviceName: "tecno", deviceModel: "Pova 5 Pro" },
  { deviceName: "tecno", deviceModel: "Pova Neo 2" },
  { deviceName: "tecno", deviceModel: "Pova 5" },
  { deviceName: "tecno", deviceModel: "Camon 20 Pro 5G" },
  { deviceName: "tecno", deviceModel: "Camon 20 Go" },
  { deviceName: "tecno", deviceModel: "Camon 20 Pro" },
  { deviceName: "tecno", deviceModel: "Pop 7" },
  { deviceName: "tecno", deviceModel: "Spark 10C" },
  { deviceName: "tecno", deviceModel: "Spark 10" },
  { deviceName: "tecno", deviceModel: "Phantom V Fold" },
  { deviceName: "tecno", deviceModel: "Pop 7 Pro" },
  { deviceName: "tecno", deviceModel: "Spark Go 2022" },
  { deviceName: "tecno", deviceModel: "Phantom X2 Pro" },
  { deviceName: "tecno", deviceModel: "Phantom X2" },
  { deviceName: "tecno", deviceModel: "Pova 4" },
  { deviceName: "tecno", deviceModel: "Pova 5 Pro" },
  { deviceName: "tecno", deviceModel: "Pova Neo 5G" },
  { deviceName: "tecno", deviceModel: "Pop 6 Pro" },
  { deviceName: "tecno", deviceModel: "Spark 8T (India)" },
  { deviceName: "tecno", deviceModel: "Spark 8" },
  { deviceName: "tecno", deviceModel: "Camon 19 Pro 5G" },
  { deviceName: "tecno", deviceModel: "Camon 19 Pro" },
  { deviceName: "tecno", deviceModel: "Camon 19" },
  { deviceName: "tecno", deviceModel: "Spark 8" },
  { deviceName: "tecno", deviceModel: "Pop 6" },
  { deviceName: "tecno", deviceModel: "Pova 5G" },
  { deviceName: "tecno", deviceModel: "Pop 5S" },
  { deviceName: "tecno", deviceModel: "Spark 10C" },
  { deviceName: "tecno", deviceModel: "Pop 6X" },
  { deviceName: "tecno", deviceModel: "Pop 6 Pro" },
  { deviceName: "tecno", deviceModel: "Spark 8 Pro" },
  { deviceName: "tecno", deviceModel: "Spark 8T" },
  { deviceName: "tecno", deviceModel: "Spark Go 2022" },
  { deviceName: "tecno", deviceModel: "Pova 4G" },
  { deviceName: "tecno", deviceModel: "Pova Neo" },
  { deviceName: "tecno", deviceModel: "Camon 18T" },
  { deviceName: "tecno", deviceModel: "Pop 5 LTE" },
  { deviceName: "tecno", deviceModel: "Pop 5C" },
  { deviceName: "tecno", deviceModel: "Camon 18i" },
  { deviceName: "tecno", deviceModel: "Spark 8P" },
  { deviceName: "tecno", deviceModel: "Camon 18 Premier" },
  { deviceName: "tecno", deviceModel: "Camon 18 P" },
  { deviceName: "tecno", deviceModel: "Spark 8" },
  { deviceName: "tecno", deviceModel: "Pop 5" },
  { deviceName: "tecno", deviceModel: "Spark Go 2021" },
  { deviceName: "tecno", deviceModel: "Spark 7T" },
  { deviceName: "tecno", deviceModel: "Phantom X" },
  { deviceName: "tecno", deviceModel: "Pova 2" },
  { deviceName: "tecno", deviceModel: "Camon 17 Pro" },
  { deviceName: "tecno", deviceModel: "Camon 17P" },
  { deviceName: "tecno", deviceModel: "Camon 17" },
  { deviceName: "tecno", deviceModel: "Spark 7 Pro" },
  { deviceName: "tecno", deviceModel: "Spark 7" },
  { deviceName: "tecno", deviceModel: "Spark 7P" },
  { deviceName: "tecno", deviceModel: "Camon 16 Pro" },
  { deviceName: "tecno", deviceModel: "Camon 16" },
  { deviceName: "tecno", deviceModel: "Camon 16S" },
  { deviceName: "tecno", deviceModel: "Spark 6 Go 2020" },
  { deviceName: "tecno", deviceModel: "Pova" },
  { deviceName: "tecno", deviceModel: "Camon 16 Premier" },
  { deviceName: "tecno", deviceModel: "Spark 6 Air" },
  { deviceName: "tecno", deviceModel: "Spark 6" },
  { deviceName: "tecno", deviceModel: "Camon 16 Pro" },
  { deviceName: "tecno", deviceModel: "Pouvoir 4 Pro" },
  { deviceName: "tecno", deviceModel: "Pouvoir 4" },
  { deviceName: "tecno", deviceModel: "Spark Power 2" },
  { deviceName: "tecno", deviceModel: "Spark 6 Air" },
  { deviceName: "tecno", deviceModel: "Spark 6 Pro" },
  { deviceName: "tecno", deviceModel: "Spark 5" },
  { deviceName: "tecno", deviceModel: "Pouvoir 4 Pro" },
  { deviceName: "tecno", deviceModel: "Spark Power 2" },
  { deviceName: "tecno", deviceModel: "Camon 15" },
  { deviceName: "tecno", deviceModel: "Camon 15 Premier" },
  { deviceName: "tecno", deviceModel: "Camon 16 Air" },
  { deviceName: "tecno", deviceModel: "Pop 5 LTE" },
  { deviceName: "tecno", deviceModel: "Camon 16 S" },
  { deviceName: "tecno", deviceModel: "Pop 2 Plus" },
  { deviceName: "tecno", deviceModel: "Spark 4 Lite" },
  { deviceName: "tecno", deviceModel: "Spark 4 Air" },
  { deviceName: "tecno", deviceModel: "Camon 12 Pro" },
  { deviceName: "tecno", deviceModel: "Camon 12" },
  { deviceName: "tecno", deviceModel: "Pop 2" },
  { deviceName: "tecno", deviceModel: "Pop 2F" },
  { deviceName: "tecno", deviceModel: "Pouvoir 3 Air" },
  { deviceName: "tecno", deviceModel: "Pouvoir 3 Plus" },
  { deviceName: "tecno", deviceModel: "Pouvoir 3" },
  { deviceName: "tecno", deviceModel: "Spark 3 Pro" },
  { deviceName: "tecno", deviceModel: "Spark 3" },
  { deviceName: "tecno", deviceModel: "Spark 3 Lite" },
  { deviceName: "tecno", deviceModel: "Pop 2 Plus" },
  { deviceName: "tecno", deviceModel: "Pop 2F" },
  { deviceName: "tecno", deviceModel: "Phantom 9" },
  { deviceName: "tecno", deviceModel: "Camon i4 KC6" },
  { deviceName: "tecno", deviceModel: "Camon i4" },
  { deviceName: "tecno", deviceModel: "Camon i4 KC2" },
  { deviceName: "tecno", deviceModel: "Camon i3 Pro" },
  { deviceName: "tecno", deviceModel: "Camon i3" },
  { deviceName: "tecno", deviceModel: "Pop 1 Lite" },
  { deviceName: "tecno", deviceModel: "Pop 1 Pro" },
  { deviceName: "tecno", deviceModel: "Pop 1 Lite" },
  { deviceName: "tecno", deviceModel: "F2 LTE" },
  { deviceName: "tecno", deviceModel: "F2" },
  { deviceName: "tecno", deviceModel: "Pop 1 Lite" },
  { deviceName: "tecno", deviceModel: "Pouvoir 2 Pro" },
  { deviceName: "tecno", deviceModel: "Pouvoir 2" },
  { deviceName: "tecno", deviceModel: "Pouvoir 1" },
  { deviceName: "tecno", deviceModel: "Spark Pro" },
  { deviceName: "tecno", deviceModel: "Spark 2" },
  { deviceName: "tecno", deviceModel: "Spark" },
  { deviceName: "tecno", deviceModel: "Camon X Pro" },
  { deviceName: "tecno", deviceModel: "Camon X" },
  { deviceName: "tecno", deviceModel: "Camon CM" },
  { deviceName: "tecno", deviceModel: "Camon CX Air" },
  { deviceName: "tecno", deviceModel: "Camon CX" },
  { deviceName: "tecno", deviceModel: "Phantom 8" },
  { deviceName: "tecno", deviceModel: "Phantom 8 Pro" },
  { deviceName: "itel", deviceModel: "itel Super Guru L1" },
  { deviceName: "itel", deviceModel: "itel S23+" },
  { deviceName: "itel", deviceModel: "itel P40 LTE" },
  { deviceName: "itel", deviceModel: "itel P40" },
  { deviceName: "itel", deviceModel: "itel A60X" },
  { deviceName: "itel", deviceModel: "itel A60L" },
  { deviceName: "itel", deviceModel: "itel P40+ LTE" },
  { deviceName: "itel", deviceModel: "itel P40+" },
  { deviceName: "itel", deviceModel: "itel P40" },
  { deviceName: "itel", deviceModel: "itel P36 Pro LTE" },
  { deviceName: "itel", deviceModel: "itel A60S" },
  { deviceName: "itel", deviceModel: "itel A60B" },
  { deviceName: "itel", deviceModel: "itel P36 Pro" },
  { deviceName: "itel", deviceModel: "itel P36" },
  { deviceName: "itel", deviceModel: "itel S23" },
  { deviceName: "itel", deviceModel: "itel Magic X" },
  { deviceName: "itel", deviceModel: "itel Magic X Play" },
  { deviceName: "itel", deviceModel: "itel A25 Pro" },
  { deviceName: "itel", deviceModel: "itel A25" },
  { deviceName: "itel", deviceModel: "itel A60S" },
  { deviceName: "itel", deviceModel: "itel S23" },
  { deviceName: "itel", deviceModel: "itel A60L" },
  { deviceName: "itel", deviceModel: "itel A60X" },
  { deviceName: "itel", deviceModel: "itel A60" },
  { deviceName: "itel", deviceModel: "itel Vision 2S" },
  { deviceName: "itel", deviceModel: "itel A60B" },
  { deviceName: "itel", deviceModel: "itel A60X" },
  { deviceName: "itel", deviceModel: "itel A60L" },
  { deviceName: "itel", deviceModel: "itel A60" },
  { deviceName: "itel", deviceModel: "itel Vision 2" },
  { deviceName: "itel", deviceModel: "itel A60S" },
  { deviceName: "itel", deviceModel: "itel A60X" },
  { deviceName: "itel", deviceModel: "itel A60L" },
  { deviceName: "itel", deviceModel: "itel A60" },
  { deviceName: "itel", deviceModel: "itel A26" },
  { deviceName: "itel", deviceModel: "itel Vision 2S" },
  { deviceName: "itel", deviceModel: "itel A60B" },
  { deviceName: "itel", deviceModel: "itel A60X" },
  { deviceName: "itel", deviceModel: "itel A60L" },
  { deviceName: "itel", deviceModel: "itel A60" },
  { deviceName: "itel", deviceModel: "itel Vision 2S" },
  { deviceName: "itel", deviceModel: "itel A60B" },
  { deviceName: "itel", deviceModel: "itel A60X" },
  { deviceName: "itel", deviceModel: "itel A60L" },
  { deviceName: "itel", deviceModel: "itel A60" },
  { deviceName: "itel", deviceModel: "itel A56 Pro" },
  { deviceName: "itel", deviceModel: "itel A56" },
  { deviceName: "itel", deviceModel: "itel P36 Pro LTE" },
  { deviceName: "itel", deviceModel: "itel P36 Pro" },
  { deviceName: "itel", deviceModel: "itel P36" },
  { deviceName: "itel", deviceModel: "itel A25 Pro" },
  { deviceName: "itel", deviceModel: "itel A25" },
  { deviceName: "itel", deviceModel: "itel A60S" },
  { deviceName: "itel", deviceModel: "itel A60B" },
  { deviceName: "itel", deviceModel: "itel P36 Pro LTE" },
  { deviceName: "itel", deviceModel: "itel P36 Pro" },
  { deviceName: "itel", deviceModel: "itel P36" },
  { deviceName: "itel", deviceModel: "itel A60" },
  { deviceName: "iPhone", deviceModel: "iPhone 15 Pro" },
  { deviceName: "iPhone", deviceModel: "iPhone 15" },
  { deviceName: "iPhone", deviceModel: "iPhone 15 Plus" },
  { deviceName: "iPhone", deviceModel: "iPhone 15 Pro Max" },
  { deviceName: "iPhone", deviceModel: "iPhone 14" },
  { deviceName: "iPhone", deviceModel: "iPhone 14 Plus" },
  { deviceName: "iPhone", deviceModel: "iPhone 14 Pro" },
  { deviceName: "iPhone", deviceModel: "iPhone 14 Pro Max" },
  { deviceName: "iPhone", deviceModel: "iPhone 13" },
  { deviceName: "iPhone", deviceModel: "iPhone 13 mini" },
  { deviceName: "iPhone", deviceModel: "iPhone 13 Pro" },
  { deviceName: "iPhone", deviceModel: "iPhone 13 Pro Max" },
  { deviceName: "iPhone", deviceModel: "iPhone 12" },
  { deviceName: "iPhone", deviceModel: "iPhone 12 mini" },
  { deviceName: "iPhone", deviceModel: "iPhone 12 Pro" },
  { deviceName: "iPhone", deviceModel: "iPhone 12 Pro Max" },
  { deviceName: "iPhone", deviceModel: "iPhone SE (2022)" },
  { deviceName: "iPhone", deviceModel: "iPhone SE" },
  { deviceName: "iPhone", deviceModel: "Watch SE (2022)" },
  { deviceName: "iPhone", deviceModel: "Watch SE" },
  { deviceName: "iPhone", deviceModel: "iPad Pro 12.9 (2022)" },
  { deviceName: "iPhone", deviceModel: "iPad Pro 11 (2022)" },
  { deviceName: "iPhone", deviceModel: "iPad Pro 12.9" },
  { deviceName: "iPhone", deviceModel: "iPad Pro 11" },
  { deviceName: "iPhone", deviceModel: "iPad Air (2022)" },
  { deviceName: "iPhone", deviceModel: "iPad Air (2021)" },
  { deviceName: "iPhone", deviceModel: "iPad mini (2021)" },
  { deviceName: "iPhone", deviceModel: "iPad mini" },
  { deviceName: "iPhone", deviceModel: "iPad (2022)" },
  { deviceName: "iPhone", deviceModel: "iPad (2021)" },
  { deviceName: "iPhone", deviceModel: "iPad" },
  { deviceName: "iPhone", deviceModel: "iPhone 11" },
  { deviceName: "iPhone", deviceModel: "iPad 10.2 (2019)" },
  { deviceName: "iPhone", deviceModel: "iPad Air (2919)" },
  { deviceName: "iPhone", deviceModel: "iPad mini (2019)" },
  { deviceName: "iPhone", deviceModel: "iPad Pro 12.9 (2018)" },
  { deviceName: "iPhone", deviceModel: "iPad Pro 11 (2018)" },
  { deviceName: "iPhone", deviceModel: "iPhone XS Max" },
  { deviceName: "iPhone", deviceModel: "iPhone XS" },
  { deviceName: "iPhone", deviceModel: "iPhone XR" },
  { deviceName: "iPhone", deviceModel: "iPad 9.7 (2018)" },
  { deviceName: "iPhone", deviceModel: "iPhone X" },
  { deviceName: "iPhone", deviceModel: "iPhone 8 Plus" },
  { deviceName: "iPhone", deviceModel: "iPhone 8" },
  { deviceName: "iPhone", deviceModel: "iPad Pro 12.9 (2017)" },
  { deviceName: "iPhone", deviceModel: "iPad Pro 10.5 (2017)" },
  { deviceName: "iPhone", deviceModel: "iPad Pro 9.7 (2017)" },
  { deviceName: "iPhone", deviceModel: "iPhone 7 Plus" },
  { deviceName: "iPhone", deviceModel: "iPhone 7" },
  { deviceName: "iPhone", deviceModel: "iPad Pro 9.7 (2016)" },
  { deviceName: "iPhone", deviceModel: "iPhone SE" },
  { deviceName: "iPhone", deviceModel: "iPhone 6s Plus" },
  { deviceName: "iPhone", deviceModel: "iPhone 6s" },
  { deviceName: "iPhone", deviceModel: "iPad Pro 12.9 (2015)" },
  { deviceName: "iPhone", deviceModel: "iPad mini 4 (2015)" },
  { deviceName: "iPhone", deviceModel: "iPad Air 2" },
  { deviceName: "iPhone", deviceModel: "iPad mini 3" },
  { deviceName: "iPhone", deviceModel: "iPhone 6 Plus" },
  { deviceName: "iPhone", deviceModel: "iPhone 6" },
  { deviceName: "iPhone", deviceModel: "iPhone 5s" },
  { deviceName: "iPhone", deviceModel: "iPhone 5c" },
  { deviceName: "iPhone", deviceModel: "iPhone 5" },
  { deviceName: "iPhone", deviceModel: "iPhone 4s" },
  { deviceName: "iPhone", deviceModel: "iPhone 4" },
  { deviceName: "iPhone", deviceModel: "iPhone 3GS" },
  { deviceName: "iPhone", deviceModel: "iPhone 3G" },
  { deviceName: "iPhone", deviceModel: "iPhone" },
  { deviceName: "iPhone", deviceModel: "iPad Air" },
  { deviceName: "iPhone", deviceModel: "iPad mini 2" },
  { deviceName: "iPhone", deviceModel: "iPad mini Wi-Fi" },
  { deviceName: "iPhone", deviceModel: "iPad mini Wi-Fi + Cellular" },
  { deviceName: "iPhone", deviceModel: "iPad 4 Wi-Fi" },
  { deviceName: "iPhone", deviceModel: "iPad 4 Wi-Fi + Cellular" },
  { deviceName: "iPhone", deviceModel: "iPad 3 Wi-Fi" },
  { deviceName: "iPhone", deviceModel: "iPad 2 Wi-Fi" },
  { deviceName: "iPhone", deviceModel: "iPad 2 Wi-Fi + 3G" },
  { deviceName: "iPhone", deviceModel: "iPad 2 CDMA" },
  { deviceName: "iPhone", deviceModel: "iPad Wi-Fi" },
  { deviceName: "iPhone", deviceModel: "iPad Wi-Fi + 3G" },
  { deviceName: "samsung", deviceModel: "M35 5G" },
  { deviceName: "samsung", deviceModel: "C55" },
  { deviceName: "samsung", deviceModel: "F55 5G" },
  { deviceName: "samsung", deviceModel: "Tab S6 Lite 2024 Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Tab S6 Lite 2024 LTE" },
  { deviceName: "samsung", deviceModel: "M55 5G" },
  { deviceName: "samsung", deviceModel: "A55" },
  { deviceName: "samsung", deviceModel: "A35" },
  { deviceName: "samsung", deviceModel: "M15 5G" },
  { deviceName: "samsung", deviceModel: "M14 4G" },
  { deviceName: "samsung", deviceModel: "F15 5G" },
  { deviceName: "samsung", deviceModel: "Tab Active5" },
  { deviceName: "samsung", deviceModel: "XCover7" },
  { deviceName: "samsung", deviceModel: "S24 Exynos" },
  { deviceName: "samsung", deviceModel: "S24+ Exynos" },
  { deviceName: "samsung", deviceModel: "S24" },
  { deviceName: "samsung", deviceModel: "S24+" },
  { deviceName: "samsung", deviceModel: "S24 Ultra" },
  { deviceName: "samsung", deviceModel: "A15 4G" },
  { deviceName: "samsung", deviceModel: "A15 5G" },
  { deviceName: "samsung", deviceModel: "Jump3" },
  { deviceName: "samsung", deviceModel: "A25" },
  { deviceName: "samsung", deviceModel: "Tab A9+ Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Tab A9+ 5G" },
  { deviceName: "samsung", deviceModel: "Tab A9 Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Tab S9+ FE Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Tab S9+ FE 5G" },
  { deviceName: "samsung", deviceModel: "Tab S9 FE Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Tab S9 FE 5G" },
  { deviceName: "samsung", deviceModel: "S23 FE SM8450" },
  { deviceName: "samsung", deviceModel: "S23 FE Exynos" },
  { deviceName: "samsung", deviceModel: "A05s" },
  { deviceName: "samsung", deviceModel: "A05" },
  { deviceName: "samsung", deviceModel: "W24" },
  { deviceName: "samsung", deviceModel: "W24 Flip" },
  { deviceName: "samsung", deviceModel: "Tab S9 Ultra 5G" },
  { deviceName: "samsung", deviceModel: "Tab S9 Ultra Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Tab S9+ 5G" },
  { deviceName: "samsung", deviceModel: "Tab S9+ Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Tab S9 5G" },
  { deviceName: "samsung", deviceModel: "Tab S9 Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Z Fold5" },
  { deviceName: "samsung", deviceModel: "Z Flip5" },
  { deviceName: "samsung", deviceModel: "M34 5G" },
  { deviceName: "samsung", deviceModel: "F54 5G" },
  { deviceName: "samsung", deviceModel: "A14 4G" },
  { deviceName: "samsung", deviceModel: "A24" },
  { deviceName: "samsung", deviceModel: "F14" },
  { deviceName: "samsung", deviceModel: "M54 5G" },
  { deviceName: "samsung", deviceModel: "A34 5G" },
  { deviceName: "samsung", deviceModel: "A54 5G" },
  { deviceName: "samsung", deviceModel: "M14 5G" },
  { deviceName: "samsung", deviceModel: "S23" },
  { deviceName: "samsung", deviceModel: "A14 5G" },
  { deviceName: "samsung", deviceModel: "S23 Ultra" },
  { deviceName: "samsung", deviceModel: "F04" },
  { deviceName: "samsung", deviceModel: "S23+" },
  { deviceName: "samsung", deviceModel: "A04" },
  { deviceName: "samsung", deviceModel: "M04" },
  { deviceName: "samsung", deviceModel: "A23 5G Japan" },
  { deviceName: "samsung", deviceModel: "A04e" },
  { deviceName: "samsung", deviceModel: "W23 Flip" },
  { deviceName: "samsung", deviceModel: "W23" },
  { deviceName: "samsung", deviceModel: "Tab Active4 Pro Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Tab Active4 Pro 5G" },
  { deviceName: "samsung", deviceModel: "A04s" },
  { deviceName: "samsung", deviceModel: "A23 5G" },
  { deviceName: "samsung", deviceModel: "Z Fold4" },
  { deviceName: "samsung", deviceModel: "Z Flip4" },
  { deviceName: "samsung", deviceModel: "M13 4G India" },
  { deviceName: "samsung", deviceModel: "M13 5G" },
  { deviceName: "samsung", deviceModel: "XCover6 Pro" },
  { deviceName: "samsung", deviceModel: "F13" },
  { deviceName: "samsung", deviceModel: "A04 Core" },
  { deviceName: "samsung", deviceModel: "M13" },
  { deviceName: "samsung", deviceModel: "Tab S6 Lite 2022 Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Quantum 3" },
  { deviceName: "samsung", deviceModel: "A33 5G" },
  { deviceName: "samsung", deviceModel: "M53 5G" },
  { deviceName: "samsung", deviceModel: "A73 5G" },
  { deviceName: "samsung", deviceModel: "A53 5G" },
  { deviceName: "samsung", deviceModel: "F23 5G" },
  { deviceName: "samsung", deviceModel: "M33 5G" },
  { deviceName: "samsung", deviceModel: "M23" },
  { deviceName: "samsung", deviceModel: "A13" },
  { deviceName: "samsung", deviceModel: "A23" },
  { deviceName: "samsung", deviceModel: "Tab S8 Ultra Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Tab S8 Ultra 5G" },
  { deviceName: "samsung", deviceModel: "Tab S8+ Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Tab S8+ 5G" },
  { deviceName: "samsung", deviceModel: "Tab S8 Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Tab S8 5G" },
  { deviceName: "samsung", deviceModel: "S22 Ultra Exynos" },
  { deviceName: "samsung", deviceModel: "S22+ Exynos" },
  { deviceName: "samsung", deviceModel: "S22 Exynos" },
  { deviceName: "samsung", deviceModel: "S21 FE SD888" },
  { deviceName: "samsung", deviceModel: "S21 FE Exynos" },
  { deviceName: "samsung", deviceModel: "S22 Ultra" },
  { deviceName: "samsung", deviceModel: "S22+" },
  { deviceName: "samsung", deviceModel: "S22" },
  { deviceName: "samsung", deviceModel: "Tab A9 LTE" },
  { deviceName: "samsung", deviceModel: "Tab A8 Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Tab A8 LTE" },
  { deviceName: "samsung", deviceModel: "A03" },
  { deviceName: "samsung", deviceModel: "W22 5G" },
  { deviceName: "samsung", deviceModel: "A13 5G" },
  { deviceName: "samsung", deviceModel: "F42 5G" },
  { deviceName: "samsung", deviceModel: "Wide5" },
  { deviceName: "samsung", deviceModel: "A21 Simple SCV49" },
  { deviceName: "samsung", deviceModel: "M52 5G" },
  { deviceName: "samsung", deviceModel: "M22" },
  { deviceName: "samsung", deviceModel: "M32 5G" },
  { deviceName: "samsung", deviceModel: "A03s" },
  { deviceName: "samsung", deviceModel: "A12 Nacho" },
  { deviceName: "samsung", deviceModel: "A52s 5G" },
  { deviceName: "samsung", deviceModel: "Z Flip3 5G" },
  { deviceName: "samsung", deviceModel: "Z Fold3" },
  { deviceName: "samsung", deviceModel: "Tab S7 FE Wi-Fi" },
  { deviceName: "samsung", deviceModel: "F22" },
  { deviceName: "samsung", deviceModel: "M21 2021" },
  { deviceName: "samsung", deviceModel: "M32" },
  { deviceName: "samsung", deviceModel: "A22 5G" },
  { deviceName: "samsung", deviceModel: "A22" },
  { deviceName: "samsung", deviceModel: "Tab A7 Lite Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Tab A7 Lite LTE" },
  { deviceName: "samsung", deviceModel: "Tab S7 FE 5G" },
  { deviceName: "samsung", deviceModel: "F52 5G" },
  { deviceName: "samsung", deviceModel: "S20 FE LTE SD865" },
  { deviceName: "samsung", deviceModel: "M42 5G" },
  { deviceName: "samsung", deviceModel: "Quantum2" },
  { deviceName: "samsung", deviceModel: "F02s" },
  { deviceName: "samsung", deviceModel: "F12" },
  { deviceName: "samsung", deviceModel: "A72" },
  { deviceName: "samsung", deviceModel: "A52" },
  { deviceName: "samsung", deviceModel: "XCover 5" },
  { deviceName: "samsung", deviceModel: "A32" },
  { deviceName: "samsung", deviceModel: "M62" },
  { deviceName: "samsung", deviceModel: "F62" },
  { deviceName: "samsung", deviceModel: "M12" },
  { deviceName: "samsung", deviceModel: "A52 5G" },
  { deviceName: "samsung", deviceModel: "M02" },
  { deviceName: "samsung", deviceModel: "A02" },
  { deviceName: "samsung", deviceModel: "A32 5G" },
  { deviceName: "samsung", deviceModel: "M02s" },
  { deviceName: "samsung", deviceModel: "S21+ 5G SD888" },
  { deviceName: "samsung", deviceModel: "S21+ 5G Exynos" },
  { deviceName: "samsung", deviceModel: "S21 5G SD888" },
  { deviceName: "samsung", deviceModel: "S21 5G Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy A02s" },
  { deviceName: "samsung", deviceModel: "Galaxy A12" },
  { deviceName: "samsung", deviceModel: "Galaxy M01s" },
  { deviceName: "samsung", deviceModel: "Galaxy Note20" },
  { deviceName: "samsung", deviceModel: "Galaxy S21 Ultra" },
  { deviceName: "samsung", deviceModel: "Galaxy Note20 Ultra 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy S21" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A7" },
  { deviceName: "samsung", deviceModel: "Galaxy Note20 Ultra" },
  { deviceName: "samsung", deviceModel: "Galaxy A51 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy A31" },
  { deviceName: "samsung", deviceModel: "Galaxy S20 FE" },
  { deviceName: "samsung", deviceModel: "Galaxy A71 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy A21s" },
  { deviceName: "samsung", deviceModel: "Galaxy A3 Core" },
  { deviceName: "samsung", deviceModel: "Galaxy A01 Core" },
  { deviceName: "samsung", deviceModel: "Galaxy M11" },
  { deviceName: "samsung", deviceModel: "Galaxy M31" },
  { deviceName: "samsung", deviceModel: "Galaxy S10 Lite" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S7" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S7+" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10 Lite" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10+" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10+ 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy Note20 Ultra 5G (Snapdragon)" },
  { deviceName: "samsung", deviceModel: "Galaxy Z Flip 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy S20 Ultra" },
  { deviceName: "samsung", deviceModel: "Galaxy S20+" },
  { deviceName: "samsung", deviceModel: "Galaxy A11" },
  { deviceName: "samsung", deviceModel: "Galaxy A21" },
  { deviceName: "samsung", deviceModel: "Galaxy A51" },
  { deviceName: "samsung", deviceModel: "Galaxy A51 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy A31" },
  { deviceName: "samsung", deviceModel: "Galaxy A41" },
  { deviceName: "samsung", deviceModel: "Galaxy A71" },
  { deviceName: "samsung", deviceModel: "Galaxy A01" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S6 Lite" },
  { deviceName: "samsung", deviceModel: "Galaxy M21" },
  { deviceName: "samsung", deviceModel: "Galaxy M31s" },
  { deviceName: "samsung", deviceModel: "Galaxy M51" },
  { deviceName: "samsung", deviceModel: "Galaxy A11" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 8.4" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S6" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 8.4 (2020)" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 10.1" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S6 Lite (2020)" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A7 Lite" },
  { deviceName: "samsung", deviceModel: "Galaxy A21" },
  { deviceName: "samsung", deviceModel: "Galaxy A31" },
  { deviceName: "samsung", deviceModel: "Galaxy A41" },
  { deviceName: "samsung", deviceModel: "Galaxy A51" },
  { deviceName: "samsung", deviceModel: "Galaxy A71" },
  { deviceName: "samsung", deviceModel: "Galaxy M01" },
  { deviceName: "samsung", deviceModel: "Galaxy M01 Core" },
  { deviceName: "samsung", deviceModel: "Galaxy S20 FE 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy Z Fold2" },
  { deviceName: "samsung", deviceModel: "Galaxy Note20 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy Note20 Ultra 5G (Snapdragon)" },
  { deviceName: "samsung", deviceModel: "Galaxy S20 Ultra" },
  { deviceName: "samsung", deviceModel: "Galaxy S20+" },
  { deviceName: "samsung", deviceModel: "Galaxy S20" },
  { deviceName: "samsung", deviceModel: "Galaxy Z Flip" },
  { deviceName: "samsung", deviceModel: "Galaxy S20 Ultra 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy S20+ 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy S20 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10+" },
  { deviceName: "samsung", deviceModel: "Galaxy S10 Lite" },
  { deviceName: "samsung", deviceModel: "Galaxy XCover Pro" },
  { deviceName: "samsung", deviceModel: "Galaxy J2 DTV" },
  { deviceName: "samsung", deviceModel: "Galaxy A9 Pro (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy A9 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy A7 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy A8 (SCV32)" },
  { deviceName: "samsung", deviceModel: "Galaxy A5 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy A5 (2016) SM-A5100" },
  { deviceName: "samsung", deviceModel: "Galaxy A3 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy Note 5 Duos" },
  { deviceName: "samsung", deviceModel: "W2016" },
  { deviceName: "samsung", deviceModel: "Galaxy J3" },
  { deviceName: "samsung", deviceModel: "Galaxy View LTE" },
  { deviceName: "samsung", deviceModel: "Galaxy View Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Galaxy On7" },
  { deviceName: "samsung", deviceModel: "Galaxy On5" },
  { deviceName: "samsung", deviceModel: "Z3" },
  { deviceName: "samsung", deviceModel: "Galaxy Active Neo" },
  { deviceName: "samsung", deviceModel: "Galaxy S5 Neo" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab E 8.0 T377V" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab E Wi-Fi 16GB" },
  { deviceName: "samsung", deviceModel: "Galaxy J1 Ace" },
  { deviceName: "samsung", deviceModel: "Galaxy J1 Ace Dual SIM" },
  { deviceName: "samsung", deviceModel: "Galaxy Core Prime VE" },
  { deviceName: "samsung", deviceModel: "Galaxy J2" },
  { deviceName: "samsung", deviceModel: "SM-G919B" },
  { deviceName: "samsung", deviceModel: "Galaxy S6 Edge+" },
  { deviceName: "samsung", deviceModel: "Galaxy Note5" },
  { deviceName: "samsung", deviceModel: "Galaxy A8 SM-A800F" },
  { deviceName: "samsung", deviceModel: "Galaxy Folder LTE" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S2 9.7" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S2 9.7 Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S2 8.0" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S2 8.0 Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 SM-J700F" },
  { deviceName: "samsung", deviceModel: "Galaxy A8" },
  { deviceName: "samsung", deviceModel: "Galaxy Grand Prime VE SM-G531F" },
  { deviceName: "samsung", deviceModel: "Galaxy Grand Prime VE SM-G531H" },
  { deviceName: "samsung", deviceModel: "Galaxy V Plus" },
  { deviceName: "samsung", deviceModel: "Galaxy S6 Duos" },
  { deviceName: "samsung", deviceModel: "Galaxy J7" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab E Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Galaxy S6 Active" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 8.0 LTE" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 8.0" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 9.7 LTE" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 9.7" },
  { deviceName: "samsung", deviceModel: "Galaxy S5 mini GT-G800F" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab 3 V" },
  { deviceName: "samsung", deviceModel: "Galaxy Win 2" },
  { deviceName: "samsung", deviceModel: "Galaxy Xcover 3" },
  { deviceName: "samsung", deviceModel: "Galaxy S6 Edge" },
  { deviceName: "samsung", deviceModel: "Galaxy S6" },
  { deviceName: "samsung", deviceModel: "Galaxy J1 4G" },
  { deviceName: "samsung", deviceModel: "Galaxy J1" },
  { deviceName: "samsung", deviceModel: "Galaxy Core Prime G360" },
  { deviceName: "samsung", deviceModel: "Galaxy Grand Neo Plus" },
  { deviceName: "samsung", deviceModel: "Z1" },
  { deviceName: "samsung", deviceModel: "Galaxy A7 Duos" },
  { deviceName: "samsung", deviceModel: "Galaxy A7" },
  { deviceName: "samsung", deviceModel: "Galaxy Grand Max" },
  { deviceName: "samsung", deviceModel: "Galaxy E7" },
  { deviceName: "samsung", deviceModel: "Galaxy E5" },
  { deviceName: "samsung", deviceModel: "Galaxy J1 mini Prime" },
  { deviceName: "samsung", deviceModel: "Galaxy J2 Prime" },
  { deviceName: "samsung", deviceModel: "Galaxy Grand Prime Plus" },
  { deviceName: "samsung", deviceModel: "W2017" },
  { deviceName: "samsung", deviceModel: "Galaxy C9 Pro" },
  { deviceName: "samsung", deviceModel: "Galaxy On Nxt" },
  { deviceName: "samsung", deviceModel: "Galaxy Note7" },
  { deviceName: "samsung", deviceModel: "Galaxy A9 Pro" },
  { deviceName: "samsung", deviceModel: "Galaxy A8 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy On8" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 10.1 (2016) with S Pen" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 10.1 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy Folder 2" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Prime" },
  { deviceName: "samsung", deviceModel: "Z2" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A (2016) Nook" },
  { deviceName: "samsung", deviceModel: "Galaxy J5 Metal" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 10.1 Advanced 64G" },
  { deviceName: "samsung", deviceModel: "Galaxy Note7 SD820" },
  { deviceName: "samsung", deviceModel: "Galaxy Note7 Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy On7 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab J" },
  { deviceName: "samsung", deviceModel: "Galaxy J2 Pro" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Metal" },
  { deviceName: "samsung", deviceModel: "Galaxy On7 Pro" },
  { deviceName: "samsung", deviceModel: "Galaxy On5 Pro" },
  { deviceName: "samsung", deviceModel: "Galaxy J1 Ace Neo" },
  { deviceName: "samsung", deviceModel: "Galaxy J2 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy J Max" },
  { deviceName: "samsung", deviceModel: "Galaxy Wide" },
  { deviceName: "samsung", deviceModel: "Galaxy J3 V" },
  { deviceName: "samsung", deviceModel: "Galaxy J3 Pro" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 10.1 (2016) Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Active" },
  { deviceName: "samsung", deviceModel: "Galaxy C7" },
  { deviceName: "samsung", deviceModel: "Galaxy C5" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 7.0" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S2 9.7 SM-T819" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S2 9.7 Wi-Fi SM-T813" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S2 8.0 SM-T719" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S2 8.0 Wi-Fi SM-T713" },
  { deviceName: "samsung", deviceModel: "Galaxy S7 G9" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 10.1 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy Xcover 3 VE" },
  { deviceName: "samsung", deviceModel: "Galaxy Express 3" },
  { deviceName: "samsung", deviceModel: "Galaxy Amp 2" },
  { deviceName: "samsung", deviceModel: "Galaxy Amp Prime" },
  { deviceName: "samsung", deviceModel: "Galaxy Express Prime" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy J5 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy A9 7.0 (2016) LTE" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 7.0 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy J1 mini" },
  { deviceName: "samsung", deviceModel: "Galaxy S7 Edge SD820" },
  { deviceName: "samsung", deviceModel: "Galaxy S7 Edge Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy S7 SD820" },
  { deviceName: "samsung", deviceModel: "Galaxy S7 Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy A3 (2016) SM-A3109" },
  { deviceName: "samsung", deviceModel: "Galaxy J1 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab E 8.0 SM-T3777" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab E 8.0 LTE" },
  { deviceName: "samsung", deviceModel: "Galaxy J3 (2016) SM-J320Y" },
  { deviceName: "samsung", deviceModel: "Galaxy J3 (2016)" },
  { deviceName: "samsung", deviceModel: "Galaxy TabPro S" },
  { deviceName: "samsung", deviceModel: "Galaxy J2 (2018)" },
  { deviceName: "samsung", deviceModel: "Galaxy S8+" },
  { deviceName: "samsung", deviceModel: "Galaxy J2 Prime (2017)" },
  { deviceName: "samsung", deviceModel: "W2018" },
  { deviceName: "samsung", deviceModel: "Galaxy A8 (2018)" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab E 8.0 SM-T378V" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab Active 2 Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Galaxy C7 Core" },
  { deviceName: "samsung", deviceModel: "Galaxy J2 (2017)" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab Active 2 LTE" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 8.0 (2017)" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 8.0 (2017) Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Galaxy C8" },
  { deviceName: "samsung", deviceModel: "Galaxy J7+" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Neo" },
  { deviceName: "samsung", deviceModel: "Galaxy Note8" },
  { deviceName: "samsung", deviceModel: "Galaxy Note8 SD835" },
  { deviceName: "samsung", deviceModel: "Leadership 8" },
  { deviceName: "samsung", deviceModel: "Galaxy S8 Active" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Nxt" },
  { deviceName: "samsung", deviceModel: "Galaxy J3 Pro (2017)" },
  { deviceName: "samsung", deviceModel: "Galaxy On Max" },
  { deviceName: "samsung", deviceModel: "Galaxy J5 Pro" },
  { deviceName: "samsung", deviceModel: "Galaxy J5 (2017)" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Max" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Pro" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 (2017)" },
  { deviceName: "samsung", deviceModel: "Galaxy J5 (2017)" },
  { deviceName: "samsung", deviceModel: "Galaxy Note FE" },
  { deviceName: "samsung", deviceModel: "Galaxy Note FE Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy J3 (2017)" },
  { deviceName: "samsung", deviceModel: "Galaxy J3 (2017) AT&T" },
  { deviceName: "samsung", deviceModel: "Z4" },
  { deviceName: "samsung", deviceModel: "Galaxy Wide2" },
  { deviceName: "samsung", deviceModel: "Galaxy Feel SC-04J" },
  { deviceName: "samsung", deviceModel: "Galaxy J5 (2017) Duos" },
  { deviceName: "samsung", deviceModel: "Galaxy Express Prime 2" },
  { deviceName: "samsung", deviceModel: "Galaxy Amp Prime 2" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Perx" },
  { deviceName: "samsung", deviceModel: "Galaxy J3 Prime" },
  { deviceName: "samsung", deviceModel: "Galaxy S8+ SD835" },
  { deviceName: "samsung", deviceModel: "Galaxy S8+ Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 V" },
  { deviceName: "samsung", deviceModel: "Galaxy C5 Pro" },
  { deviceName: "samsung", deviceModel: "Galaxy S8 SD835" },
  { deviceName: "samsung", deviceModel: "Galaxy S8 Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy Xcover 4" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S3 Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S3" },
  { deviceName: "samsung", deviceModel: "Galaxy J2 Ace" },
  { deviceName: "samsung", deviceModel: "Galaxy C7 Pro" },
  { deviceName: "samsung", deviceModel: "Galaxy J3 Emerge" },
  { deviceName: "samsung", deviceModel: "Galaxy A7 (2017)" },
  { deviceName: "samsung", deviceModel: "Galaxy A5 (2017)" },
  { deviceName: "samsung", deviceModel: "Galaxy A3 (2017)" },
  { deviceName: "samsung", deviceModel: "Galaxy A30" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Top" },
  { deviceName: "samsung", deviceModel: "Galaxy J4 Core" },
  { deviceName: "samsung", deviceModel: "W2019" },
  { deviceName: "samsung", deviceModel: "Galaxy J4 Core" },
  { deviceName: "samsung", deviceModel: "Galaxy A9s" },
  { deviceName: "samsung", deviceModel: "Galaxy Feel2" },
  { deviceName: "samsung", deviceModel: "Galaxy J6 DTV" },
  { deviceName: "samsung", deviceModel: "Galaxy A9 (2018)" },
  { deviceName: "samsung", deviceModel: "Galaxy A6s" },
  { deviceName: "samsung", deviceModel: "Galaxy A7 (2018)" },
  { deviceName: "samsung", deviceModel: "Galaxy J6+" },
  { deviceName: "samsung", deviceModel: "Galaxy J4+" },
  { deviceName: "samsung", deviceModel: "Galaxy J2 Core" },
  { deviceName: "samsung", deviceModel: "Galaxy On6" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 10.5" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 10.5 LTE" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 10.5 Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Galaxy Note9 Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy Note9 SD845" },
  { deviceName: "samsung", deviceModel: "Galaxy Grand Prime Pro (2018)" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Star" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S4" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S4 Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab Advanced2" },
  { deviceName: "samsung", deviceModel: "Galaxy Sol 3" },
  { deviceName: "samsung", deviceModel: "Galaxy On8" },
  { deviceName: "samsung", deviceModel: "Galaxy J2 Core 2nd" },
  { deviceName: "samsung", deviceModel: "Galaxy J3 V 3rd" },
  { deviceName: "samsung", deviceModel: "Galaxy Jean" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Refine" },
  { deviceName: "samsung", deviceModel: "Galaxy J3 Achieve" },
  { deviceName: "samsung", deviceModel: "Galaxy Amp Prime 3" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Star" },
  { deviceName: "samsung", deviceModel: "Galaxy A8 Star" },
  { deviceName: "samsung", deviceModel: "Galaxy A9 Star" },
  { deviceName: "samsung", deviceModel: "Galaxy A9 Star Lite" },
  { deviceName: "samsung", deviceModel: "W2018" },
  { deviceName: "samsung", deviceModel: "Galaxy S Light Luxury Edition" },
  { deviceName: "samsung", deviceModel: "Galaxy J8" },
  { deviceName: "samsung", deviceModel: "Galaxy J6 (2018)" },
  { deviceName: "samsung", deviceModel: "Galaxy J4 (2018)" },
  { deviceName: "samsung", deviceModel: "Galaxy A6+ (2018)" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Prime 2 (2018)" },
  { deviceName: "samsung", deviceModel: "Galaxy A6 (2018)" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Duo" },
  { deviceName: "samsung", deviceModel: "Galaxy J7 Prime 2" },
  { deviceName: "samsung", deviceModel: "Galaxy S9+" },
  { deviceName: "samsung", deviceModel: "Galaxy S9" },
  { deviceName: "samsung", deviceModel: "Galaxy S9 Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy S9 SD845" },
  { deviceName: "samsung", deviceModel: "Galaxy S9 Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy S9+ SD845" },
  { deviceName: "samsung", deviceModel: "Galaxy A01" },
  { deviceName: "samsung", deviceModel: "Galaxy A71" },
  { deviceName: "samsung", deviceModel: "Galaxy A51" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab Active Pro" },
  { deviceName: "samsung", deviceModel: "W20 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy XCover FieldPro" },
  { deviceName: "samsung", deviceModel: "Galaxy A70s" },
  { deviceName: "samsung", deviceModel: "Galaxy A20s" },
  { deviceName: "samsung", deviceModel: "Galaxy M10s" },
  { deviceName: "samsung", deviceModel: "Galaxy Fold 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy A90 5G" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10 5G Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10 5G SD855" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10+ 5G Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10+ 5G SD855" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S6" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10 Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10 SD855" },
  { deviceName: "samsung", deviceModel: "Galaxy A10s" },
  { deviceName: "samsung", deviceModel: "Galaxy A10e" },
  { deviceName: "samsung", deviceModel: "Galaxy A50s" },
  { deviceName: "samsung", deviceModel: "Galaxy M30s" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 8.0 (2019) LTE" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 8.0 (2019) Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Galaxy A30s" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10+ Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy Note10+ SD855" },
  { deviceName: "samsung", deviceModel: "Galaxy Jean2" },
  { deviceName: "samsung", deviceModel: "Galaxy Wide4" },
  { deviceName: "samsung", deviceModel: "Galaxy A20" },
  { deviceName: "samsung", deviceModel: "Galaxy Xcover 4s" },
  { deviceName: "samsung", deviceModel: "Galaxy M40" },
  { deviceName: "samsung", deviceModel: "Galaxy View2" },
  { deviceName: "samsung", deviceModel: "Galaxy A60" },
  { deviceName: "samsung", deviceModel: "Galaxy A40s" },
  { deviceName: "samsung", deviceModel: "Galaxy A80" },
  { deviceName: "samsung", deviceModel: "Galaxy A20e" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 8.0 with S Pen" },
  { deviceName: "samsung", deviceModel: "Galaxy A70" },
  { deviceName: "samsung", deviceModel: "Galaxy A40" },
  { deviceName: "samsung", deviceModel: "Galaxy A2 Core" },
  { deviceName: "samsung", deviceModel: "Galaxy Fold" },
  { deviceName: "samsung", deviceModel: "Galaxy S10 5G Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy S10 5G SD855" },
  { deviceName: "samsung", deviceModel: "Galaxy S10+ Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy S10+ SD855" },
  { deviceName: "samsung", deviceModel: "Galaxy S10 Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy S10 SD855" },
  { deviceName: "samsung", deviceModel: "Galaxy S10e Exynos" },
  { deviceName: "samsung", deviceModel: "Galaxy S10e SD855" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 10.1 2019 Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 10.1 2019 LTE" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S5e Wi-Fi" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab S5e LTE" },
  { deviceName: "samsung", deviceModel: "Galaxy A10" },
  { deviceName: "samsung", deviceModel: "Galaxy A30" },
  { deviceName: "samsung", deviceModel: "Galaxy J2 Pure" },
  { deviceName: "samsung", deviceModel: "Galaxy A50" },
  { deviceName: "samsung", deviceModel: "Galaxy A9 Pro (2019)" },
  { deviceName: "samsung", deviceModel: "Galaxy M30" },
  { deviceName: "samsung", deviceModel: "Galaxy M10" },
  { deviceName: "samsung", deviceModel: "Galaxy M20" },
  { deviceName: "samsung", deviceModel: "Galaxy Tab A 8.0 2018 LTE" },
];
